import { useState, useEffect } from 'react';

export type Language = 'en' | 'es' | 'fr' | 'de' | 'pt' | 'zh' | 'ja' | 'ko' | 'ru' | 'ar';

const listeners = new Set<(lang: Language) => void>();

let currentLanguage: Language =
  (typeof window !== 'undefined' &&
    (localStorage.getItem('language') as Language)) ||
  (typeof navigator !== 'undefined'
    ? (navigator.language.split('-')[0] as Language)
    : 'en');

if (!currentLanguage) currentLanguage = 'en';

// Complete translation dictionary
export const translations: Record<Language, Record<string, string>> = {
  en: {
    // Header
    'header.title': 'CRYPTOCARDS',
    'header.subtitle': 'Design and create on-chain, non-custodial crypto gift cards. No wallet connection required.',
    'header.claimButton': 'CLAIM YOUR CARD',
    'header.claimHint': '🎁 Received a CRYPTOCARD? Click here to claim your card!',
    'header.buyButton': 'BUY $CRYPTOCARDS',
    'header.ca': 'CA:',
    'header.copy': 'COPY',
    
    // Progress bar
    'progress.design': '1. Design',
    'progress.fund': '2. Fund & Lock',
    'progress.gift': '3. Gift',
    
    // Card Designer
    'designer.tokenAddress': 'TOKEN ADDRESS (the CA of the token you wish to load onto the CRYPTOCARD)',
    'designer.tokenPlaceholder': 'Paste contract address...',
    'designer.message': 'Card Message',
    'designer.messagePlaceholder': 'Write your message...',
    'designer.font': 'Font Style',
    'designer.expiry': 'Set Expiry',
    'designer.expiryHint': 'Optional: Set expiry date',
    'designer.expiryDate': 'Expiry Date',
    'designer.imageSearch': 'Image Search',
    'designer.searchPlaceholder': 'Search images...',
    'designer.useGifs': 'USE GIFS',
    'designer.uploadImage': 'UPLOAD CUSTOM IMAGE',
    'designer.refreshImages': 'REFRESH',
    'designer.createButton': 'SAVE DESIGN & CONTINUE',
    'designer.creating': 'CREATING...',
    
    // CryptoCard
    'card.noExpiry': 'NO EXPIRATION DATE',
    'card.scratch': 'SCRATCH',
    
    // Instructions
    'instructions.title': 'HOW TO CREATE A CRYPTOCARD',
    'instructionstwo.title': 'How do CRYPTOCARDS work?',
    'instructions.design': 'Design:',
    'instructions.designDesc': 'Select token, image, message & expiry',
    'instructions.fund': 'Fund:',
    'instructions.fundDesc': 'Send tokens to deposit address',
    'instructions.lock': 'Lock:',
    'instructions.lockDesc': 'Finalize card (irreversible)',
    'instructions.share': 'Gift:',
    'instructions.shareDesc': 'Share with recipient',
    'instructions.taxNote': '0.5% tax on all cards & buys burns $CRYPTOCARDS',
    
    // Funding Panel
    'funding.title': 'FUND YOUR CARD',
    'funding.cardId': 'CARD ID',
    'funding.cvvWarning': '⚠️ Keep CVV private until gifting!',
    'funding.hide': 'HIDE',
    'funding.show': 'SHOW',
    'funding.depositAddress': 'DEPOSIT ADDRESS',
    'funding.funded': 'Card Funded - Ready to Lock!',
    'funding.waiting': 'Waiting for funds...',
    'funding.fundedAmount': 'Funded:',
    
    // Buttons
    'button.lockAndShare': 'LOCK CARD AND SHARE',
    'button.cardLocked': 'CARD LOCKED',
    'button.lockWarning': '⚠️ LOCKING IS IRREVERSIBLE. ENSURE DESIGN AND FUNDING ARE FINAL.',
    'button.reset': 'RESET & CREATE NEW',
    
    // Login Panel
    'login.title': 'USER LOGIN',
    'login.createTitle': 'CREATE ACCOUNT',
    'login.username': 'Username',
    'login.usernamePlaceholder': 'Enter username...',
    'login.email': 'Email',
    'login.emailOptional': '(Optional)',
    'login.emailPlaceholder': 'Optional for notifications...',
    'login.emailHint': 'Providing an email allows you to reset your password and receive notifications.',
    'login.password': 'Password',
    'login.passwordPlaceholder': 'Enter password...',
    'login.loginButton': 'LOGIN',
    'login.registerButton': 'REGISTER',
    'login.loading': 'LOADING...',
    'login.noAccount': "Don't have an account? Register",
    'login.hasAccount': 'Already have an account? Login',
    
    // User Dashboard
    'dashboard.title': 'USER DASHBOARD',
    'dashboard.logout': 'LOGOUT',
    'dashboard.myCards': 'MY CARDS',
    'dashboard.noCards': 'No cards yet',
    'dashboard.changeEmail': 'CHANGE EMAIL',
    'dashboard.newEmail': 'New Email',
    'dashboard.updateEmail': 'UPDATE EMAIL',
    'dashboard.emailUpdated': 'Email updated successfully!',
    
    // Audit Section
    'audit.title': 'ON-CHAIN CARD AUDIT',
    'audit.help': 'View verifiable on-chain actions for each card',
    'audit.cardId': 'Card ID',
    'audit.lookup': 'LOOKUP',
    'audit.created': 'Created',
    'audit.funded': 'Funded',
    'audit.locked': 'Locked',
    'audit.redeemed': 'Redeemed',
    'audit.viewOnSolscan': 'View on Solscan',
    'audit.pending': 'Pending',
    'audit.noCard': 'Enter a Card ID to view on-chain actions',
    
    // Public Dashboard
    'public.title': 'PUBLIC DASHBOARD',
    'public.help': 'View real-time statistics across all CRYPTOCARDS.',
    'public.totalFunded': 'Total Cards Funded',
    'public.totalBurned': 'Total Value Burned',
    
    // Footer
    'footer.poweredBy': 'Powered by Solana',
    'footer.copyright': '© 2025 CRYPTOCARDS',
    'footer.creator': 'Created by retireded_dev',
    'footer.rights': 'All rights reserved',
    'footer.terms': 'Terms of Service',
    'footer.privacy': 'Privacy Policy',
    'footer.docs': 'Documentation',
    
    // Modals
    'claim.title': 'CLAIM CARD',
    'claim.cardId': 'CARD ID',
    'claim.cardIdPlaceholder': 'Enter Card ID (xxxx-xxxx)',
    'claim.pullCard': 'PULL CARD',
    'claim.wallet': 'YOUR WALLET ADDRESS',
    'claim.walletPlaceholder': 'Enter your Solana wallet address...',
    'claim.cvv': 'CVV (5-digit code)',
    'claim.cvvPlaceholder': 'Scratch the back of the card to reveal CVV',
    'claim.cvvHint': '💡 Click "SCRATCH" on the back of the card preview above',
    'claim.claimButton': 'CLAIM FUNDS',
    'claim.claiming': 'CLAIMING...',
    'claim.close': 'CLOSE',
    'claim.loading': 'LOADING...',
    'claim.preview': 'Card Preview',
    'claim.status': 'Status:',
    'claim.locked': 'Locked',
    'claim.unlocked': 'Unlocked',
    'claim.tokenAmount': 'Token Amount:',
    'claim.value': 'Value:',
    
    'share.title': 'SHARE YOUR CARD',
    'share.claimLink': 'CLAIM LINK',
    'share.copyLink': 'COPY LINK',
    'share.email': 'EMAIL',
    'share.telegram': 'TELEGRAM',
    'share.twitter': 'TWITTER/X',
    'share.showQr': 'SHOW QR',
    'share.close': 'CLOSE',
    
    // Security Banner
    'security.message': 'We will NEVER contact you or DM you first. Always verify you are on the correct URL.',
  },
  es: {
    'header.title': 'CRYPTOCARDS',
    'header.subtitle': 'Diseña y crea tarjetas de regalo crypto on-chain y sin custodia. Sin conexión de billetera.',
    'header.claimButton': 'RECLAMAR TU TARJETA',
    'header.claimHint': '🎁 ¿Recibiste una CRYPTOCARD? ¡Haz clic aquí para reclamarla!',
    'header.buyButton': 'COMPRAR $CRYPTOCARDS',
    'header.ca': 'CA:',
    'header.copy': 'COPIAR',
    'progress.design': '1. Diseñar',
    'progress.fund': '2. Fondear y Bloquear',
    'progress.gift': '3. Regalar',
    'designer.tokenAddress': 'DIRECCIÓN DEL TOKEN (el CA del token que desea cargar en la CRYPTOCARD)',
    'designer.tokenPlaceholder': 'Pegar dirección del contrato...',
    'designer.message': 'Mensaje de la Tarjeta',
    'designer.messagePlaceholder': 'Escribe tu mensaje...',
    'designer.font': 'Estilo de Fuente',
    'designer.expiry': 'Establecer Vencimiento',
    'designer.imageSearch': 'Buscar Imágenes',
    'designer.searchPlaceholder': 'Buscar imágenes...',
    'designer.useGifs': 'USAR GIFS',
    'designer.uploadImage': 'SUBIR IMAGEN',
    'designer.refreshImages': 'ACTUALIZAR',
    'designer.createButton': 'GUARDAR DISEÑO Y CONTINUAR',
    'designer.creating': 'CREANDO...',
    'instructions.title': '¿Cómo funcionan las CRYPTOCARDS?',
    'instructions.design': 'Diseñar:',
    'instructions.designDesc': 'Selecciona token, imagen, mensaje y vencimiento',
    'instructions.fund': 'Fondear:',
    'instructions.fundDesc': 'Envía tokens a la dirección de depósito',
    'instructions.lock': 'Bloquear:',
    'instructions.lockDesc': 'Finalizar tarjeta (irreversible)',
    'instructions.share': 'Regalar:',
    'instructions.shareDesc': 'Compartir con el destinatario',
    'instructions.taxNote': '0.5% de impuesto en todas las tarjetas y compras quema $CRYPTOCARDS',
    'funding.title': 'FONDEA TU TARJETA',
    'funding.cardId': 'ID DE TARJETA',
    'funding.cvvWarning': '⚠️ ¡Mantén el CVV privado hasta regalar!',
    'funding.hide': 'OCULTAR',
    'funding.show': 'MOSTRAR',
    'funding.depositAddress': 'DIRECCIÓN DE DEPÓSITO',
    'funding.funded': '¡Tarjeta Fondeada - Lista para Bloquear!',
    'funding.waiting': 'Esperando fondos...',
    'funding.fundedAmount': 'Fondeado:',
    'button.lockAndShare': 'BLOQUEAR TARJETA Y COMPARTIR',
    'button.cardLocked': 'TARJETA BLOQUEADA',
    'button.lockWarning': '⚠️ EL BLOQUEO ES IRREVERSIBLE. ASEGÚRESE DE QUE EL DISEÑO Y EL FONDEO SEAN FINALES.',
    'button.reset': 'REINICIAR Y CREAR NUEVA',
    'login.title': 'INICIAR SESIÓN',
    'login.createTitle': 'CREAR CUENTA',
    'login.username': 'Usuario',
    'login.usernamePlaceholder': 'Ingresa usuario...',
    'login.email': 'Correo',
    'login.emailOptional': '(Opcional)',
    'login.emailPlaceholder': 'Opcional para notificaciones...',
    'login.password': 'Contraseña',
    'login.passwordPlaceholder': 'Ingresa contraseña...',
    'login.loginButton': 'INGRESAR',
    'login.registerButton': 'REGISTRARSE',
    'login.loading': 'CARGANDO...',
    'login.noAccount': '¿No tienes cuenta? Regístrate',
    'login.hasAccount': '¿Ya tienes cuenta? Inicia sesión',
    'dashboard.title': 'PANEL DE USUARIO',
    'dashboard.logout': 'CERRAR SESIÓN',
    'dashboard.myCards': 'MIS TARJETAS',
    'dashboard.noCards': 'Sin tarjetas aún',
    'dashboard.changeEmail': 'CAMBIAR CORREO',
    'dashboard.newEmail': 'Nuevo Correo',
    'dashboard.updateEmail': 'ACTUALIZAR CORREO',
    'dashboard.emailUpdated': '¡Correo actualizado exitosamente!',
    'audit.title': 'AUDITORÍA ON-CHAIN',
    'audit.help': 'Ver acciones verificables on-chain para cada tarjeta',
    'audit.cardId': 'ID de Tarjeta',
    'audit.lookup': 'BUSCAR',
    'audit.created': 'Creada',
    'audit.funded': 'Fondeada',
    'audit.locked': 'Bloqueada',
    'audit.redeemed': 'Reclamada',
    'audit.viewOnSolscan': 'Ver en Solscan',
    'audit.pending': 'Pendiente',
    'audit.noCard': 'Ingresa un ID de Tarjeta para ver acciones on-chain',
    'public.title': 'PANEL PÚBLICO',
    'public.help': 'Ver estadísticas en tiempo real de todas las CRYPTOCARDS.',
    'public.totalFunded': 'Total de Tarjetas Fondeadas',
    'public.totalBurned': 'Valor Total Quemado',
    'footer.poweredBy': 'Impulsado por Solana',
    'footer.copyright': '© 2025 CRYPTOCARDS',
    'footer.creator': 'Creado por retireded_dev',
    'footer.rights': 'Todos los derechos reservados',
    'claim.title': 'RECLAMAR TARJETA',
    'claim.cardId': 'ID DE TARJETA',
    'claim.cardIdPlaceholder': 'Ingresa ID de Tarjeta (xxxx-xxxx)',
    'claim.pullCard': 'OBTENER TARJETA',
    'claim.wallet': 'TU DIRECCIÓN DE BILLETERA',
    'claim.walletPlaceholder': 'Ingresa tu dirección de billetera Solana...',
    'claim.cvv': 'CVV (código de 5 dígitos)',
    'claim.cvvPlaceholder': 'Raspa la parte trasera de la tarjeta para revelar el CVV',
    'claim.cvvHint': '💡 Haz clic en "RASPAR" en la parte trasera de la vista previa',
    'claim.claimButton': 'RECLAMAR FONDOS',
    'claim.claiming': 'RECLAMANDO...',
    'claim.close': 'CERRAR',
    'claim.loading': 'CARGANDO...',
    'claim.preview': 'Vista Previa',
    'claim.status': 'Estado:',
    'claim.locked': 'Bloqueada',
    'claim.unlocked': 'Desbloqueada',
    'claim.tokenAmount': 'Cantidad de Token:',
    'claim.value': 'Valor:',
    'share.title': 'COMPARTE TU TARJETA',
    'share.claimLink': 'ENLACE DE RECLAMO',
    'share.copyLink': 'COPIAR ENLACE',
    'share.email': 'CORREO',
    'share.telegram': 'TELEGRAM',
    'share.twitter': 'TWITTER/X',
    'share.showQr': 'MOSTRAR QR',
    'share.close': 'CERRAR',
    'security.message': 'NUNCA te contactaremos o te enviaremos un DM primero. Siempre verifica que estás en la URL correcta.',
  },
  fr: {
    'header.title': 'CRYPTOCARDS',
    'header.subtitle': 'Concevez et créez des cartes-cadeaux crypto on-chain et non-custodial. Aucune connexion de portefeuille requise.',
    'header.claimButton': 'RÉCLAMER VOTRE CARTE',
    'header.claimHint': '🎁 Reçu une CRYPTOCARD? Cliquez ici pour la réclamer!',
    'header.buyButton': 'ACHETER $CRYPTOCARDS',
    'header.ca': 'CA:',
    'header.copy': 'COPIER',
    'progress.design': '1. Concevoir',
    'progress.fund': '2. Financer et Verrouiller',
    'progress.gift': '3. Offrir',
    'designer.tokenAddress': 'ADRESSE DU TOKEN (le CA du token que vous souhaitez charger sur la CRYPTOCARD)',
    'designer.tokenPlaceholder': 'Coller l\'adresse du contrat...',
    'designer.message': 'Message de la Carte',
    'designer.messagePlaceholder': 'Écrivez votre message...',
    'designer.font': 'Style de Police',
    'designer.expiry': 'Définir Expiration',
    'designer.imageSearch': 'Recherche d\'Images',
    'designer.searchPlaceholder': 'Rechercher des images...',
    'designer.useGifs': 'UTILISER GIFS',
    'designer.uploadImage': 'TÉLÉCHARGER IMAGE',
    'designer.refreshImages': 'ACTUALISER',
    'designer.createButton': 'SAUVEGARDER LE DESIGN ET CONTINUER',
    'designer.creating': 'CRÉATION...',
    'instructions.title': 'Comment fonctionnent les CRYPTOCARDS?',
    'instructions.design': 'Concevoir:',
    'instructions.designDesc': 'Sélectionnez token, image, message et expiration',
    'instructions.fund': 'Financer:',
    'instructions.fundDesc': 'Envoyez des tokens à l\'adresse de dépôt',
    'instructions.lock': 'Verrouiller:',
    'instructions.lockDesc': 'Finaliser la carte (irréversible)',
    'instructions.share': 'Offrir:',
    'instructions.shareDesc': 'Partager avec le destinataire',
    'instructions.taxNote': '0.5% de taxe sur toutes les cartes et achats brûle $CRYPTOCARDS',
    'funding.title': 'FINANCEZ VOTRE CARTE',
    'funding.cardId': 'ID DE CARTE',
    'funding.cvvWarning': '⚠️ Gardez le CVV privé jusqu\'au don!',
    'funding.hide': 'CACHER',
    'funding.show': 'MONTRER',
    'funding.depositAddress': 'ADRESSE DE DÉPÔT',
    'funding.funded': 'Carte Financée - Prête à Verrouiller!',
    'funding.waiting': 'En attente de fonds...',
    'funding.fundedAmount': 'Financé:',
    'button.lockAndShare': 'VERROUILLER LA CARTE ET PARTAGER',
    'button.cardLocked': 'CARTE VERROUILLÉE',
    'button.lockWarning': '⚠️ LE VERROUILLAGE EST IRRÉVERSIBLE. ASSUREZ-VOUS QUE LE DESIGN ET LE FINANCEMENT SONT FINAUX.',
    'button.reset': 'RÉINITIALISER ET CRÉER NOUVELLE',
    'login.title': 'CONNEXION',
    'login.createTitle': 'CRÉER UN COMPTE',
    'login.username': 'Nom d\'utilisateur',
    'login.usernamePlaceholder': 'Entrez le nom d\'utilisateur...',
    'login.email': 'Email',
    'login.emailOptional': '(Optionnel)',
    'login.password': 'Mot de passe',
    'login.passwordPlaceholder': 'Entrez le mot de passe...',
    'login.loginButton': 'CONNEXION',
    'login.registerButton': 'S\'INSCRIRE',
    'login.loading': 'CHARGEMENT...',
    'login.noAccount': 'Pas de compte? Inscrivez-vous',
    'login.hasAccount': 'Déjà un compte? Connectez-vous',
    'dashboard.title': 'TABLEAU DE BORD',
    'dashboard.logout': 'DÉCONNEXION',
    'dashboard.myCards': 'MES CARTES',
    'dashboard.noCards': 'Pas encore de cartes',
    'dashboard.changeEmail': 'CHANGER EMAIL',
    'dashboard.newEmail': 'Nouvel Email',
    'dashboard.updateEmail': 'METTRE À JOUR EMAIL',
    'dashboard.emailUpdated': 'Email mis à jour avec succès!',
    'audit.title': 'AUDIT ON-CHAIN',
    'audit.help': 'Voir les actions vérifiables on-chain pour chaque carte',
    'audit.cardId': 'ID de Carte',
    'audit.lookup': 'RECHERCHER',
    'audit.created': 'Créée',
    'audit.funded': 'Financée',
    'audit.locked': 'Verrouillée',
    'audit.redeemed': 'Réclamée',
    'audit.viewOnSolscan': 'Voir sur Solscan',
    'audit.pending': 'En attente',
    'audit.noCard': 'Entrez un ID de Carte pour voir les actions on-chain',
    'public.title': 'TABLEAU PUBLIC',
    'public.help': 'Voir les statistiques en temps réel de toutes les CRYPTOCARDS.',
    'public.totalFunded': 'Total des Cartes Financées',
    'public.totalBurned': 'Valeur Totale Brûlée',
    'footer.poweredBy': 'Propulsé par Solana',
    'footer.copyright': '© 2025 CRYPTOCARDS',
    'footer.creator': 'Créé par retireded_dev',
    'footer.rights': 'Tous droits réservés',
    'claim.title': 'RÉCLAMER LA CARTE',
    'claim.cardId': 'ID DE CARTE',
    'claim.pullCard': 'OBTENIR LA CARTE',
    'claim.wallet': 'VOTRE ADRESSE DE PORTEFEUILLE',
    'claim.cvv': 'CVV (code à 5 chiffres)',
    'claim.claimButton': 'RÉCLAMER LES FONDS',
    'claim.close': 'FERMER',
    'claim.loading': 'CHARGEMENT...',
    'claim.status': 'Statut:',
    'claim.locked': 'Verrouillée',
    'claim.unlocked': 'Déverrouillée',
    'security.message': 'Nous ne vous contacterons JAMAIS en premier. Vérifiez toujours l\'URL.',
  },
  de: {
    'header.title': 'CRYPTOCARDS',
    'header.subtitle': 'Entwerfen und erstellen Sie On-Chain, nicht-verwahrende Krypto-Geschenkkarten. Keine Wallet-Verbindung erforderlich.',
    'header.claimButton': 'KARTE EINLÖSEN',
    'header.claimHint': '🎁 Eine CRYPTOCARD erhalten? Klicken Sie hier zum Einlösen!',
    'header.buyButton': 'KAUFEN $CRYPTOCARDS',
    'header.ca': 'CA:',
    'header.copy': 'KOPIEREN',
    'progress.design': '1. Entwerfen',
    'progress.fund': '2. Finanzieren & Sperren',
    'progress.gift': '3. Verschenken',
    'designer.tokenAddress': 'TOKEN-ADRESSE (die CA des Tokens, das Sie auf die CRYPTOCARD laden möchten)',
    'designer.tokenPlaceholder': 'Vertragsadresse einfügen...',
    'designer.message': 'Kartennachricht',
    'designer.messagePlaceholder': 'Schreiben Sie Ihre Nachricht...',
    'instructions.title': 'Wie funktionieren CRYPTOCARDS?',
    'button.lockWarning': '⚠️ DAS SPERREN IST UNWIDERRUFLICH. STELLEN SIE SICHER, DASS DESIGN UND FINANZIERUNG FINAL SIND.',
    'dashboard.title': 'BENUTZER-DASHBOARD',
    'audit.title': 'ON-CHAIN AUDIT',
    'audit.help': 'Überprüfbare On-Chain-Aktionen für jede Karte anzeigen',
    'public.title': 'ÖFFENTLICHES DASHBOARD',
    'public.help': 'Echtzeit-Statistiken aller CRYPTOCARDS anzeigen.',
    'security.message': 'Wir werden Sie NIEMALS zuerst kontaktieren. Überprüfen Sie immer die URL.',
  },
  pt: {
    'header.title': 'CRYPTOCARDS',
    'header.subtitle': 'Crie cartões presente crypto on-chain e sem custódia. Sem conexão de carteira.',
    'header.claimButton': 'RESGATAR SEU CARTÃO',
    'header.claimHint': '🎁 Recebeu uma CRYPTOCARD? Clique para resgatar!',
    'header.buyButton': 'COMPRAR $CRYPTOCARDS',
    'header.ca': 'CA:',
    'header.copy': 'COPIAR',
    'progress.design': '1. Design',
    'progress.fund': '2. Financiar e Bloquear',
    'progress.gift': '3. Presentear',
    'designer.tokenAddress': 'ENDEREÇO DO TOKEN (o CA do token que você deseja carregar na CRYPTOCARD)',
    'designer.tokenPlaceholder': 'Colar endereço do contrato...',
    'designer.message': 'Mensagem do Cartão',
    'designer.messagePlaceholder': 'Escreva sua mensagem...',
    'instructions.title': 'Como funcionam as CRYPTOCARDS?',
    'button.lockWarning': '⚠️ O BLOQUEIO É IRREVERSÍVEL. CERTIFIQUE-SE DE QUE O DESIGN E O FINANCIAMENTO SÃO FINAIS.',
    'dashboard.title': 'PAINEL DO USUÁRIO',
    'audit.title': 'AUDITORIA ON-CHAIN',
    'audit.help': 'Ver ações verificáveis on-chain para cada cartão',
    'public.title': 'PAINEL PÚBLICO',
    'public.help': 'Ver estatísticas em tempo real de todas as CRYPTOCARDS.',
    'security.message': 'NUNCA entraremos em contato primeiro. Sempre verifique a URL.',
  },
  zh: {
    'header.title': 'CRYPTOCARDS',
    'header.subtitle': '设计和创建链上非托管加密礼品卡。无需连接钱包。',
    'header.claimButton': '领取您的卡片',
    'header.claimHint': '🎁 收到了CRYPTOCARD？点击这里领取！',
    'header.buyButton': '购买 $CRYPTOCARDS',
    'header.ca': 'CA:',
    'header.copy': '复制',
    'progress.design': '1. 设计',
    'progress.fund': '2. 充值并锁定',
    'progress.gift': '3. 赠送',
    'designer.tokenAddress': '代币地址（您希望加载到CRYPTOCARD上的代币CA）',
    'designer.tokenPlaceholder': '粘贴合约地址...',
    'designer.message': '卡片信息',
    'designer.messagePlaceholder': '写下您的信息...',
    'designer.font': '字体样式',
    'designer.expiry': '设置到期',
    'designer.imageSearch': '图片搜索',
    'designer.searchPlaceholder': '搜索图片...',
    'designer.useGifs': '使用GIF',
    'designer.uploadImage': '上传自定义图片',
    'designer.refreshImages': '刷新',
    'designer.createButton': '保存设计并继续',
    'designer.creating': '创建中...',
    'instructions.title': 'CRYPTOCARDS如何运作？',
    'instructions.design': '设计：',
    'instructions.designDesc': '选择代币、图片、消息和到期日',
    'instructions.fund': '充值：',
    'instructions.fundDesc': '将代币发送到存款地址',
    'instructions.lock': '锁定：',
    'instructions.lockDesc': '完成卡片（不可逆）',
    'instructions.share': '赠送：',
    'instructions.shareDesc': '与收款人分享',
    'instructions.taxNote': '所有卡片和购买收取0.5%税费用于销毁$CRYPTOCARDS',
    'funding.title': '为您的卡片充值',
    'funding.cardId': '卡片ID',
    'funding.cvvWarning': '⚠️ 在赠送前保持CVV私密！',
    'funding.hide': '隐藏',
    'funding.show': '显示',
    'funding.depositAddress': '存款地址',
    'funding.funded': '卡片已充值 - 准备锁定！',
    'funding.waiting': '等待资金...',
    'funding.fundedAmount': '已充值：',
    'button.lockAndShare': '锁定卡片并分享',
    'button.cardLocked': '卡片已锁定',
    'button.lockWarning': '⚠️ 锁定是不可逆的。确保设计和资金是最终的。',
    'button.reset': '重置并创建新卡',
    'login.title': '用户登录',
    'login.createTitle': '创建账户',
    'login.username': '用户名',
    'login.usernamePlaceholder': '输入用户名...',
    'login.email': '邮箱',
    'login.emailOptional': '（可选）',
    'login.password': '密码',
    'login.passwordPlaceholder': '输入密码...',
    'login.loginButton': '登录',
    'login.registerButton': '注册',
    'login.loading': '加载中...',
    'login.noAccount': '没有账户？注册',
    'login.hasAccount': '已有账户？登录',
    'dashboard.title': '用户仪表板',
    'dashboard.logout': '登出',
    'dashboard.myCards': '我的卡片',
    'dashboard.noCards': '还没有卡片',
    'dashboard.changeEmail': '更改邮箱',
    'dashboard.newEmail': '新邮箱',
    'dashboard.updateEmail': '更新邮箱',
    'dashboard.emailUpdated': '邮箱更新成功！',
    'audit.title': '链上审计',
    'audit.help': '查看每张卡片的可验证链上操作',
    'audit.cardId': '卡片ID',
    'audit.lookup': '查询',
    'audit.created': '已创建',
    'audit.funded': '已充值',
    'audit.locked': '已锁定',
    'audit.redeemed': '已领取',
    'audit.viewOnSolscan': '在Solscan上查看',
    'audit.pending': '待处理',
    'audit.noCard': '输入卡片ID以查看链上操作',
    'public.title': '公共仪表板',
    'public.help': '查看所有CRYPTOCARDS的实时统计数据。',
    'public.totalFunded': '已充值卡片总数',
    'public.totalBurned': '已销毁总价值',
    'footer.poweredBy': '由Solana提供支持',
    'footer.copyright': '© 2025 CRYPTOCARDS',
    'footer.creator': '由retireded_dev创建',
    'footer.rights': '保留所有权利',
    'claim.title': '领取卡片',
    'claim.cardId': '卡片ID',
    'claim.pullCard': '获取卡片',
    'claim.wallet': '您的钱包地址',
    'claim.cvv': 'CVV（5位数代码）',
    'claim.claimButton': '领取资金',
    'claim.close': '关闭',
    'claim.loading': '加载中...',
    'claim.status': '状态：',
    'claim.locked': '已锁定',
    'claim.unlocked': '未锁定',
    'security.message': '我们永远不会主动联系您。请始终验证URL。',
  },
  ja: {
    'header.title': 'CRYPTOCARDS',
    'header.subtitle': 'オンチェーン、非カストディアルの暗号ギフトカードを作成。ウォレット接続不要。',
    'header.claimButton': 'カードを請求',
    'header.claimHint': '🎁 CRYPTOCARDを受け取りましたか？クリックして請求！',
    'header.buyButton': '$CRYPTOCARDSを購入',
    'header.ca': 'CA:',
    'header.copy': 'コピー',
    'progress.design': '1. デザイン',
    'progress.fund': '2. 資金投入＆ロック',
    'progress.gift': '3. ギフト',
    'designer.tokenAddress': 'トークンアドレス（CRYPTOCARDにロードしたいトークンのCA）',
    'designer.tokenPlaceholder': 'コントラクトアドレスを貼り付け...',
    'designer.message': 'カードメッセージ',
    'designer.messagePlaceholder': 'メッセージを書く...',
    'instructions.title': 'CRYPTOCARDSの仕組み',
    'button.lockWarning': '⚠️ ロックは取り消し不可能です。デザインと資金が最終であることを確認してください。',
    'dashboard.title': 'ユーザーダッシュボード',
    'audit.title': 'オンチェーン監査',
    'audit.help': '各カードの検証可能なオンチェーンアクションを表示',
    'public.title': 'パブリックダッシュボード',
    'public.help': 'すべてのCRYPTOCARDSのリアルタイム統計を表示。',
    'security.message': '私たちから先に連絡することはありません。常にURLを確認してください。',
  },
  ko: {
    'header.title': 'CRYPTOCARDS',
    'header.subtitle': '온체인, 비수탁 암호화폐 기프트 카드를 디자인하고 생성하세요. 지갑 연결 불필요.',
    'header.claimButton': '카드 청구하기',
    'header.claimHint': '🎁 CRYPTOCARD를 받으셨나요? 여기를 클릭하여 청구하세요!',
    'header.buyButton': '$CRYPTOCARDS 구매',
    'header.ca': 'CA:',
    'header.copy': '복사',
    'progress.design': '1. 디자인',
    'progress.fund': '2. 자금 조달 및 잠금',
    'progress.gift': '3. 선물',
    'designer.tokenAddress': '토큰 주소 (CRYPTOCARD에 로드하려는 토큰의 CA)',
    'designer.tokenPlaceholder': '계약 주소 붙여넣기...',
    'designer.message': '카드 메시지',
    'designer.messagePlaceholder': '메시지 작성...',
    'instructions.title': 'CRYPTOCARDS는 어떻게 작동하나요?',
    'button.lockWarning': '⚠️ 잠금은 되돌릴 수 없습니다. 디자인과 자금이 최종인지 확인하세요.',
    'dashboard.title': '사용자 대시보드',
    'audit.title': '온체인 감사',
    'audit.help': '각 카드에 대한 검증 가능한 온체인 작업 보기',
    'public.title': '공개 대시보드',
    'public.help': '모든 CRYPTOCARDS의 실시간 통계를 봅니다.',
    'security.message': '저희가 먼저 연락하는 일은 절대 없습니다. 항상 URL을 확인하세요.',
  },
  ru: {
    'header.title': 'CRYPTOCARDS',
    'header.subtitle': 'Создавайте криптоподарочные карты на блокчейне без хранения. Подключение кошелька не требуется.',
    'header.claimButton': 'ПОЛУЧИТЬ КАРТУ',
    'header.claimHint': '🎁 Получили CRYPTOCARD? Нажмите здесь чтобы получить!',
    'header.buyButton': 'КУПИТЬ $CRYPTOCARDS',
    'header.ca': 'CA:',
    'header.copy': 'КОПИРОВАТЬ',
    'progress.design': '1. Дизайн',
    'progress.fund': '2. Пополнить и Заблокировать',
    'progress.gift': '3. Подарить',
    'designer.tokenAddress': 'АДРЕС ТОКЕНА (CA токена, который вы хотите загрузить на CRYPTOCARD)',
    'designer.tokenPlaceholder': 'Вставить адрес контракта...',
    'designer.message': 'Сообщение Карты',
    'designer.messagePlaceholder': 'Напишите ваше сообщение...',
    'instructions.title': 'Как работают CRYPTOCARDS?',
    'button.lockWarning': '⚠️ БЛОКИРОВКА НЕОБРАТИМА. УБЕДИТЕСЬ, ЧТО ДИЗАЙН И ФИНАНСИРОВАНИЕ ОКОНЧАТЕЛЬНЫЕ.',
    'dashboard.title': 'ПАНЕЛЬ ПОЛЬЗОВАТЕЛЯ',
    'audit.title': 'АУДИТ НА БЛОКЧЕЙНЕ',
    'audit.help': 'Просмотр проверяемых действий на блокчейне для каждой карты',
    'public.title': 'ПУБЛИЧНАЯ ПАНЕЛЬ',
    'public.help': 'Просмотр статистики всех CRYPTOCARDS в реальном времени.',
    'security.message': 'Мы НИКОГДА не свяжемся с вами первыми. Всегда проверяйте URL.',
  },
  ar: {
    'header.title': 'CRYPTOCARDS',
    'header.subtitle': 'صمم وأنشئ بطاقات هدايا العملات المشفرة على السلسلة بدون حفظ. لا حاجة لربط المحفظة.',
    'header.claimButton': 'استرداد بطاقتك',
    'header.claimHint': '🎁 هل استلمت CRYPTOCARD؟ انقر هنا للاسترداد!',
    'header.buyButton': 'شراء $CRYPTOCARDS',
    'header.ca': 'CA:',
    'header.copy': 'نسخ',
    'progress.design': '1. تصميم',
    'progress.fund': '2. تمويل وقفل',
    'progress.gift': '3. إهداء',
    'designer.tokenAddress': 'عنوان الرمز (CA للرمز الذي تريد تحميله على CRYPTOCARD)',
    'designer.tokenPlaceholder': 'لصق عنوان العقد...',
    'designer.message': 'رسالة البطاقة',
    'designer.messagePlaceholder': 'اكتب رسالتك...',
    'instructions.title': 'كيف تعمل CRYPTOCARDS؟',
    'button.lockWarning': '⚠️ القفل لا رجعة فيه. تأكد من أن التصميم والتمويل نهائيان.',
    'dashboard.title': 'لوحة المستخدم',
    'audit.title': 'تدقيق على السلسلة',
    'audit.help': 'عرض الإجراءات القابلة للتحقق على السلسلة لكل بطاقة',
    'public.title': 'لوحة عامة',
    'public.help': 'عرض إحصائيات في الوقت الفعلي لجميع CRYPTOCARDS.',
    'security.message': 'لن نتواصل معك أولاً أبداً. تحقق دائماً من الرابط.',
  },
};

export function t(key: string, lang?: Language): string {
  const language = lang || currentLanguage;
  return translations[language]?.[key] || translations['en']?.[key] || key;
}

export function getLanguage(): Language {
  return currentLanguage;
}

export function setLanguageValue(lang: Language) {
  currentLanguage = lang;
  localStorage.setItem('language', lang);
  listeners.forEach((cb) => cb(lang));
}

export function subscribeLanguage(cb: (lang: Language) => void) {
  listeners.add(cb);
  return () => listeners.delete(cb);
}

export function useLanguage() {
  const [language, setLang] = useState<Language>(getLanguage());

  useEffect(() => {
    const unsub = subscribeLanguage(setLang);
    return () => { unsub(); };
  }, []);

  const setLanguage = (lang: Language) => {
    setLanguageValue(lang);
  };

  return { language, setLanguage, t: (key: string) => t(key, language) };
}
